export const POPULAR_PRESENTS_2025 = [
    "Jurassic World Interactive Hatching Dino",
    "Little Live Pets Gotta Go Giraffe",
    "Disney Stitch Plush",
    "Bluey Plush",
    "LEGO Moana Set",
    "LEGO Minecraft Set",
    "LEGO Fortnite Set",
    "Toniebox 2",
    "Build-A-Bear Stuffing Station",
    "MushMeez Taba Squishies",
    "Smartphone-Controlled Paper Airplane Kit",
    "Camp Snap Screen-Free Camera",
    "Apple AirPods Pro (2nd Gen)",
    "Sony WH-1000XM5 Headphones",
    "Bose SoundLink Flex Speaker",
    "Amazon Smart Thermostat",
    "Philips Hue Smart Lighting Kit",
    "Ring Video Doorbell",
    "TP-Link Kasa Security Camera",
    "Fitbit Charge 6",
    "Theragun Mini 2.0",
    "Ember Temperature Control Smart Mug 2",
    "Apple AirTag",
    "Lumi Portable Entertainment System",
    "PlayStation 5 Console",
    "Nintendo Switch OLED",
    "HORL 3 Rolling Knife Sharpener",
    "HexClad Nonstick Pan",
    "Le Creuset Dutch Oven",
    "Engraved Acacia Wood Breadboard",
    "DASH My Mug Ice Cream Maker",
    "Dash Mini Waffle Maker",
    "Mini Jacquemus Handbag",
    "Retro Jordan Sneakers",
    "Gold Hoop Earrings with Gemstones",
    "Ray-Ban Meta Smart Glasses",
    "Faux Leather Moto Jacket",
    "Shearling Lined Coat",
    "Leopard Print Scarf",
    "Oversized Cashmere Sweater",
    "Corduroy Trousers",
    "Burberry Check Scarf",
    "Stella McCartney Falabella Bag",
    "Manolo Blahnik Hangisi Pumps",
    "Personalized Initial Necklace",
    "Oura Ring Gen 4",
    "Ninja CREAMi Ice Cream Maker",
    "Stanley Quencher H2.0 FlowState Tumbler",
    "Kindle Paperwhite Signature Edition",
    "Fujifilm Instax Mini 12"
];
