export const POPULAR_PRESENTS_2025 = [
    "Holographic Smart Watch",
    "Levitating Bonsai Tree",
    "AI-Powered Robot Dog",
    "Virtual Reality Headset Pro",
    "Self-Lacing Sneakers",
    "Drone Camera 8K",
    "Smart Garden System",
    "Portable Laser Projector",
    "Neural Interface Gaming Headset",
    "3D Printing Pen Deluxe",
    "Solar Powered Backpack",
    "Foldable Electric Scooter",
    "Smart Mirror",
    "Interactive Globe",
    "Modular Synthesizer Kit",
    "Hydroponic Herb Garden",
    "Transparent OLED TV",
    "Voice-Activated Coffee Maker",
    "Augmented Reality Glasses",
    "Personal Air Purifier Necklace",
    "Smart Yoga Mat",
    "Digital Art Frame",
    "Wireless Charging Desk Organizer",
    "Noise-Canceling Sleep Buds",
    "Smart Water Bottle",
    "Electric Skateboard",
    "Retro Arcade Machine",
    "Instant Camera with AR Filters",
    "Smart Telescope",
    "Bionic Bird Drone",
    "Coding Robot for Kids",
    "Smart Luggage with Follow Mode",
    "Portable Espresso Machine",
    "Levitating Moon Lamp",
    "Smart Jump Rope",
    "Bone Conduction Headphones",
    "Pocket-Sized Synthesizer",
    "Smart Rubik's Cube",
    "Digital Notebook Tablet",
    "Portable Solar Charger",
    "Smart Bike Helmet",
    "Interactive Storytelling Bear",
    "Gesture Control Armband",
    "Smart Plant Pot",
    "Modular Phone Case",
    "Portable Karaoke Microphone",
    "Smart Chess Board",
    "Electric Unicycle",
    "Underwater Drone",
    "Smart Doorbell with Face Rec",
    "Laser Keyboard",
    "Smart Sleep Mask",
    "Portable Photo Printer",
    "Smart Guitar",
    "Electric Drift Kart",
    "Smart Pet Feeder",
    "Interactive Wall LED Panels",
    "Smart Wallet",
    "Portable AC Unit",
    "Smart Umbrella",
    "Electric Surfboard",
    "Smart Golf Club Sensor",
    "Digital Tape Measure",
    "Smart Fishing Rod",
    "Electric Roller Skates",
    "Smart Tennis Racket",
    "Portable washing machine",
    "Smart Binoculars",
    "Electric Snowboard",
    "Smart Ski Goggles",
    "Portable Campfire",
    "Smart Tent",
    "Electric Jet Ski",
    "Smart Life Jacket",
    "Portable Hammock Stand",
    "Smart Cooler",
    "Electric Grill",
    "Smart Picnic Basket",
    "Portable Blender",
    "Smart Toaster",
    "Electric Kettle with App",
    "Smart Fridge Magnet",
    "Portable Dishwasher",
    "Smart Oven",
    "Electric Fondue Set",
    "Smart Cutting Board",
    "Portable Ice Maker",
    "Smart Sous Vide",
    "Electric Wok",
    "Smart Spice Rack",
    "Portable Pizza Oven",
    "Smart Knife Sharpener",
    "Electric Can Opener",
    "Smart Wine Opener",
    "Portable Coffee Grinder",
    "Smart Tea Infuser",
    "Electric Milk Frother",
    "Smart Food Scale",
    "Portable Juicer"
];
